Feature: Add Employee

Background:
  # Given user is able to navigate and access to HRMS page
  When user enters valid username
  And user enters valid password
  And user click on login button
  Then user logins
  When user clicks on PIM
  And user clicks on Add Employee
  Then user is able to add new employees

  @Smoke @Regression @Addemployee
  Scenario: Add employee with autogenerated ID
    When user enters firstname
    And user is able to enter middlename
    And user enters lastname
    And user see that ID is autogenerated
    And user clicks on save button
    Then new page is opened
    And user can see new employee added with firstname and lastname entered and ID

  @Regression @Addemployee
  Scenario: Add employee with manually provided ID
    When user enters firstname
    And user is able to enter middlename
    And user enters lastname
    And user enters ID
    And user clicks on save button
    Then new page is opened
    And user can see new employee added with firstname, lastname and ID entered

    @negative
  Scenario: Add employee without a firstname
    And user is able to enter middlename
    And user see that ID is autogenerated
    And user enters lastname
    And user clicks on save button
    Then user see required firstname
    And new employee is not created

 @negative
  Scenario: Add employee without a lastname
    When user enters firstname
    And user clicks on save button
    Then user see required lastname
    And new employee is not created

  @negative
  Scenario: Add employee with existing ID
    When user enters firstname
    And user enters lastname
    And user enters duplicate ID
    And user clicks on save button
    Then user sees an error message
    And new employee is not created