Feature: Add Employee

Background:
  # Given user is able to navigate and access to HRMS page
  When user enters "admin" and "Hum@nhrm123"
  And user click on login button
  Then user logins
  When user clicks on PIM
  And user clicks on Add Employee
  Then user is navigated to the Add Employee page

  @Smoke @Regression @Addemployee @2
  Scenario Outline: Add employee with autogenerated ID
    When user enters employees "<firstname>" and "<lastname>"
    And user is able to enter middlename
    And user see that ID is autogenerated
    And user clicks on save button
    Then new page is opened
    And user can see new employee added with firstname and lastname entered and ID
    Examples:
      |firstname |lastname|
      |Boris  |Grebenshikov|
      |Elliot |Smith|


  @Regression @Addemployee @2
  Scenario Outline: Add employee with manually provided ID
    When user enters employees "<firstname>" and "<lastname>"
    And user is able to enter middlename
    And user enters ID
    And user clicks on save button
    Then new page is opened
    And user can see new employee added with firstname and lastname entered and ID
    Examples:
      | firstname | lastname |
      |Boris  |Grebenshikov|
      |Elliot |Smith|
      |Sid    |Vicious|

  @negative @2
  Scenario Outline: Add employee without a firstname or lastname
    When user enters employees "<firstname>" and "<lastname>"
    And user is able to enter middlename
    And user see that ID is autogenerated
    And user clicks on save button
    Then user see required "<message>"
    And new employee is not created
    Examples:
      | firstname | lastname | message|
      |Boris      |          |Required|
      |           |Grebenshikov|Required|

  @negative @2
  Scenario Outline: Add employee with existing ID
    When user enters employees "<firstname>" and "<lastname>"
    And user enters a "<duplicate ID>"
    And user clicks on save button
    Then user sees an error message
    And new employee is not created
    Examples:
      | firstname | lastname | duplicate ID |
      |Boris  |Grebenshikov|2128506         |

